### ISSUE TITLE
label of the displayable version of the stepper is broken

### ISSUE THREAD

**Issue by hxpaul** [holidayextras/ui-toolkit#119]
This pr https://github.com/holidayextras/ui-toolkit/pull/101 added code to hide the label of the stepper component, but that label is used for the displayable version of the stepper value.
cc @richardstevens @jodiedoubleday

**Comment by jodiedoubleday** [comment]
I would argue that the component is not broken, the implementation you are referring to it broken.
We have a PR here https://github.com/holidayextras/ui-toolkit/pull/120 (needs code review) that removes the hardcoded wording and removes the duplicate label.

**Comment by jodiedoubleday** [comment]
fixed
