### ISSUE TITLE
we need to change the label of the stepper

### ISSUE THREAD

**Issue by hxpaul** [holidayextras/ui-toolkit#85]
We have a requirement for tripapp-product-hotels to change the displayed value within the stepper from just a number to a number and  a label, "4 Adults" for example.

**Comment by hxpaul** [comment]
Make it an option for the middle of the stepper to be a dropdown?
https://github.com/holidayextras/tripapp-product-parking/issues/10

**Comment by lukehansell** [comment]
Not fixing as iterating on existing tech

**Comment by hxpaul** [comment]
when this one needs doing sounds like it will be done by the trips pod
